* Intro

org-toc is a utility to have an up-to-date table of contents in the
org files without exporting (useful primarily for readme files on
GitHub).

It is similar to the [[https://github.com/ardumont/markdown-toc][markdown-toc]] package, but for works for org
files.

* Table of Contents                                                     :TOC:
 - [[#intro][Intro]]
 - [[#installation][Installation]]
 - [[#use][Use]]

* Installation

- *TBD*

* Use

If you put the following line into your .emacs file:

#+BEGIN_SRC emacs-lisp
  (add-hook 'before-save-hook 'ot-insert-toc)
#+END_SRC

Then every time you'll be saving an org file, the first headline with
a :TOC: tag will be updated with the current table of contents.

To add a TOC tag, you can use the command =org-set-tags-command=.

In addition to the simple :TOC: tag, you can also use the following
tag formats:

- :TOC@2: - sets the max depth of the headlines in the table of
  contents to 2 (the default)

- :TOC@2@gh: - sets the max depth as in above and also uses the
  GitHub-style hrefs in the table of contents (the default). The other
  supported href style is 'org', which is the default org style (you
  can use C-c C-o to go to the headline at point).
